### ISSUE TITLE
Class Twig_Extension not found

### ISSUE THREAD

**Issue by WebVPF** [wintercms/wn-debugbar-plugin#11]
An error occurs in **Winter CMS 1.2** when using the plugin on the frontend.

![2022-06-09_002252](https://user-images.githubusercontent.com/61043464/172719847-d0d0ba1b-d5ce-43b8-9540-e9e7c01043ba.jpg)

**Comment by LukeTowers** [comment]
Try updating the plugin. 🤷 It's already been fixed in main.

**Comment by WebVPF** [comment]
@LukeTowers I did a fresh install of the plugin. The plugin had to be removed as it breaks the frontend (gives an error).

**Comment by LukeTowers** [comment]
@WebVPF can you confirm that the code you have running that isn't working is indeed the latest version from github and includes the changes in https://github.com/wintercms/wn-debugbar-plugin/commit/6d9403199ba5837bd40b17db0e879167fce93502?

**Comment by WebVPF** [comment]
@LukeTowers You're right. Updated as you showed - now the plugin works correctly.
Thank you!
