### ISSUE TITLE
Debugbar resource urls does does not work

### ISSUE THREAD

**Issue by khalidchawtany** [wintercms/wn-debugbar-plugin#12]
I have installed the latest release of Winter 1.2 and Debugbar plugin.

However, the stylesheets and javascript endpoints are reported as not found although they are shown in the route:list !

![Screen Shot 2022-07-20 at 12 27 50 PM](https://user-images.githubusercontent.com/1681606/179948261-3284b173-8f36-47c1-8c27-25e34be22cbe.png)

![Screen Shot 2022-07-20 at 12 28 41 PM](https://user-images.githubusercontent.com/1681606/179948467-8c373a2d-d76b-4028-9c2e-db2087c52b62.png)

**Comment by lex0r** [comment]
@khalidchawtany  I found a solution but not sure if it's the best one. At least it works for me.

I commented this line in Plugin.php
`App::register(\Winter\Debugbar\Classes\ServiceProvider::class);` 

and instead added the following to `register()` method:
`$this->app->register(\Winter\Debugbar\Classes\ServiceProvider::class);`

**Comment by khalidchawtany** [comment]
I added the routes manually in routes.php and it works. However, it is expected to work without hacks. I didn’t know how to do a proper fix else I would have sent a pr.

**Comment by lex0r** [comment]
@bennothommo Winter 1.2.0 release states

> Added two new events (system.beforeRoute and system.route) that fire before and after the system route registration respectively and moved the registration of the Backend and CMS module routes to be after the system route registration. The CMS module's routes should now always be the last routes registered regardless of what happens.

I wonder if this is related because when debugging {slug?} still came before _debugbar/* routes.
