### ISSUE TITLE
Basic and AJAX handler report method fails on basic "Class not found"

### ISSUE THREAD

**Issue by RomainMazB** [wintercms/wn-debugbar-plugin#2]
Hi!
I'll try to debug this one but I don't have much time atm so I create an issue to be sure to not lose the track of this.

When a "Class not found" error is raised, the debugbar throws this exception and make the page to crash instantly.

> "Argument 1 passed to Winter\Storm\Foundation\Exception\Handler::report() must be an instance of Exception, instance of TypeError given, called in /media/maz/Nouveau nom/websites/maz-digital/plugins/winter/debugbar/vendor/illuminate/routing/Pipeline.php on line 49" on line 44 of /media/maz/Nouveau nom/websites/maz-digital/vendor/winter/storm/src/Foundation/Exception/Handler.php

The only way to "correctly" display my error is to dd it when it occurs 🤷🏼‍♂️ :
```php
try {
  // ... Some failing code
} catch (\Throwable $e) {
  dd($e);
  \Log::error($e);
  Flash::error($e->getMessage());
  throw $e;
}
```

It seems to only happens on `Error` type, not on `Exception` (obviously when you read the error message).

**Comment by LukeTowers** [comment]
Where in the lifecycle is this exception thrown for this to be triggered? Just tested it locally (although with Ignition as the error page) and didn't get this result.

**Comment by RomainMazB** [comment]
The error is thrown from a plugin's component in my case and also happen on ajax call to the same component

**Comment by RomainMazB** [comment]
@LukeTowers I finally close this as I've just discovered it wasn't directly a debugbar issue.

Don't know exactly what's in cause here but if I deactivate Offline.Speedy plugin, it suddenly work as it should.

Not sure it comes directly from Speedy or the Nginx config of my local machine: Speedy doesn't work with Nginx as it's based on a .htaccess file. Maybe the fact that Speedy can't act as it should make a middleware fail at some point.
