### ISSUE TITLE
Installation via composer install the RainLab version

### ISSUE THREAD

**Issue by RomainMazB** [wintercms/wn-debugbar-plugin#4]
Probably due to the fact that [the last tagged release is the 3.1.1](https://github.com/wintercms/wn-debugbar-plugin/releases).

Installation via composer is totally wrong: create a `plugins/wn-debugbar` folder with a `Plugin.php` file namespaced under `RainLab`

**Comment by bennothommo** [comment]
@RomainMazB I've pushed out tag `v4.0.0` which should hopefully resolve this. Let me know if it doesn't and I'll re-open.
