### ISSUE TITLE
Signin to backend/forgot password/restore/cancel results in erroneous url

### ISSUE THREAD

**Issue by DaleStanbrough** [wintercms/wn-debugbar-plugin#5]
A vanilla installation of WinterCMS (running on MAMP Pro).

Select "Sign in to the Backend" > "Forgot your password" > "Restore"

...results in a plain (non css) "Winter CMS/Enter your login" page.

Clicking on either "Restore" or "Cancel" results in a URL of...

http://:8888/backend/backend/auth/restore

**Comment by bennothommo** [comment]
@DaleStanbrough is this a fault within Winter CMS itself, or the Debugbar plugin?

**Comment by LukeTowers** [comment]
@DaleStanbrough what is your app.url set to?

**Comment by DaleStanbrough** [comment]
Hi, 

No idea. 

This was a vanilla installation of WinterCMS with me just exploring it.

I haven’t installed Debugbar (assuming it doesn’t come with it).

Dale


Here are some screenshots…



https://d.pr/f/zLI3Cy <https://d.pr/f/zLI3Cy>

I can send them to you not in an archive if you prefer.


Dale

**Comment by DaleStanbrough** [comment]
I’m presuming you are asking what

config > app.php > url

is, which is…

 'url' => 'http://localhost’,


Dale

**Comment by LukeTowers** [comment]
Looks like your localhost is http://winter:8888, in which case you should set your app.url value to that

**Comment by DaleStanbrough** [comment]
Ah, my apologies for the invalid bug report 

:-(


Dale

**Comment by bennothommo** [comment]
@DaleStanbrough no probs - we're all here to help :)
